kind: pipeline
type: docker
name: build

steps:
- name: build  
  image: plugins/docker
  commands:
      - pwd
      - cd /drone/src
      - scp -r * /data 
trigger:
  event:
    - push
    - custom
    - pull_request
