kind: pipeline
type: docker
name: build

steps:
- name: build  
  image: plugins/docker
  commands:
      - pwd
      - cd /drone/src
      - ls 
      - scp -r . /opt
      - ls /opt
trigger:
  event:
    - push
    - custom
    - pull_request
